version: "3.3"

services:
  imagen_mongo:
    container_name: imagen_mongo
    image: mongo:latest
    tty: true
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - ./.init-mongorc:/docker-entrypoint-initdb.d/init-mongorc.js:ro
      - ./me-dump-predictdb:/me-dump-predictdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: imagen
      MONGO_INITDB_ROOT_PASSWORD: imagen
      MONGO_INITDB_DATABASE: imagen
    networks:
      - imagen_net

  imagen_mongo_express:
    container_name: imagen_mongo_express
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - imagen_mongo
    ports:
      - 9091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: imagen
      ME_CONFIG_MONGODB_ADMINPASSWORD: imagen
      ME_CONFIG_MONGODB_AUTH_DATABASE: imagen
      ME_CONFIG_MONGODB_AUTH_USERNAME: imagen
      ME_CONFIG_MONGODB_AUTH_PASSWORD: imagen
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: imagen_mongo
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - imagen_net

  imagen_redis:
    container_name: imagen_redis
    image: redis
    restart: unless-stopped
    depends_on:
      - imagen_mongo
      - imagen_mongo_express
    ports:
      - 6389:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - imagen_net

volumes:
  redis-data:
networks:
  imagen_net:
